### ISSUE TITLE
double 3dview window

### ISSUE THREAD

**Issue by HernandoMV** [mobie/platybrowser-datasets#56]
Reproducible error trying to visualize gene expression, ganglia segmentation, and neuropil segmentation.
The browser opens 2 3Dviewer windows displaying the information separately. Clicking the 'V' checkbox twice on 'neuropil' (to try bring it to the other window) displays the following error:

```
Adding source: sbem-6dpf-1-whole-raw...
Adding source: prospr-6dpf-1-whole-arx...
Adding source: sbem-6dpf-1-whole-segmented-ganglia...
Adding source: sbem-6dpf-1-whole-segmented-neuropil...
3D [dev] 1.6.0-scijava-3-SNAPSHOT-pre11-daily-experimental daily

nFrames = 1
nFrames = 1
J3dI18N: Error looking up: GroupRetained2
java.util.concurrent.ExecutionException: org.scijava.java3d.MultipleParentException: GroupRetained2
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at ij3d.Image3DUniverse.addContent(Image3DUniverse.java:1746)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.showSourceInVolumeViewer(PlatyBrowserSourcesPanel.java:223)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.updateSource3dView(PlatyBrowserSourcesPanel.java:90)
	at de.embl.cba.platynereis.platybrowser.SourcesDisplayUI$2.lambda$actionPerformed$0(SourcesDisplayUI.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.scijava.java3d.MultipleParentException: GroupRetained2
	at org.scijava.java3d.GroupRetained.checkValidChild(GroupRetained.java:464)
	at org.scijava.java3d.GroupRetained.addChild(GroupRetained.java:473)
	at org.scijava.java3d.Group.addChild(Group.java:282)
	at ij3d.Image3DUniverse.addContentToScene(Image3DUniverse.java:1724)
	at ij3d.Image3DUniverse.access$300(Image3DUniverse.java:84)
	at ij3d.Image3DUniverse$5.call(Image3DUniverse.java:1772)
	at ij3d.Image3DUniverse$5.call(Image3DUniverse.java:1767)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

**Comment by constantinpape** [comment]
Thanks for reporting this, Hernando.
I will check if I can reproduce it and if it's due to one of my recent changes, as I initially suspected,
or due to something else.

**Comment by constantinpape** [comment]
I think this issue is fixed.
