### ISSUE TITLE
Issue when adding ganglia_ids table to segmentation table in platyBrowser

### ISSUE THREAD

**Issue by constantinpape** [mobie/platybrowser-datasets#62]
```
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 2
	at de.embl.cba.tables.TableColumns.orderedStringColumnsFromTableFile(TableColumns.java:160)
	at de.embl.cba.tables.TableColumns.openAndOrderNewColumns(TableColumns.java:337)
	at de.embl.cba.tables.TableUIs.openTableForMergingUI(TableUIs.java:143)
	at de.embl.cba.tables.view.TableRowsTableView.lambda$null$4(TableRowsTableView.java:421)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by constantinpape** [comment]
might be related to #56

**Comment by K-Meech** [comment]
I think this was an issue with missing values in the table (pandas automatically writes them as "" which can't be parsed). I think I've fixed this now (I also added the new ganglia names to the table)
@constantinpape could you pull the changes to the arendt lab server, and check this doesn't error anymore?

**Comment by constantinpape** [comment]
Yes, works now. Thanks!
