### ISSUE TITLE
Error with Open MoBIE Project..

### ISSUE THREAD

**Issue by K-Meech** [mobie/platybrowser-datasets#64]
Opening the mobie project (from usual remote location) leads to error copied below:
Running on Windows 10 - I wonder if this has any relation to: https://github.com/mobie/mobie-viewer-fiji/issues/62

java.io.FileNotFoundException: https://raw.githubusercontent.com/mobie-org/platybrowser-datasets/tree/master/data/master/data/datasets.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at java.net.URL.openStream(URL.java:1045)
	at de.embl.cba.tables.FileAndUrlUtils.getInputStream(FileAndUrlUtils.java:102)
	at de.embl.cba.mobie.dataset.DatasetsParser.datasetsFromFile(DatasetsParser.java:36)
	at de.embl.cba.mobie.dataset.DatasetsParser.datasetsFromDataSource(DatasetsParser.java:18)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:75)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:59)
	at de.embl.cba.mobie.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:19)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] Module threw exception
java.lang.UnsupportedOperationException: Could not open or parse datasets file: https://raw.githubusercontent.com/mobie-org/platybrowser-datasets/tree/master/data/master/data/datasets.json
	at de.embl.cba.mobie.dataset.DatasetsParser.datasetsFromDataSource(DatasetsParser.java:29)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:75)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:59)
	at de.embl.cba.mobie.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:19)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by constantinpape** [comment]
I tried with the latest version from the MoBIE update site and it works on Linux.

Looking The problem is that the file https://raw.githubusercontent.com/mobie-org/platybrowser-datasets/tree/master/data/master/data/datasets.json does not exist, it should be:
https://raw.githubusercontent.com/mobie/platybrowser-datasets/master/data/datasets.json

@K-Meech Maybe you are using the wrong url? Could you try with the following in 'Open MoBIE project ...':
https://github.com/mobie/platybrowser-datasets

**Comment by K-Meech** [comment]
That works! Weird that I had the other url for some reason... I just checked with a new fiji installation / mobie download, and the default url that appears is the correct one:  https://github.com/mobie/platybrowser-datasets.
