### ISSUE TITLE
Error with opening cell segmentation from local project

### ISSUE THREAD

**Issue by K-Meech** [mobie/platybrowser-datasets#65]
Opening the platybrowser from local files (arendt server version) works, but then leads to the error below when the cell segmentation is viewed. Possibly related to: https://github.com/mobie/mobie-viewer-fiji/issues/62? (running on Windows 10)

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at de.embl.cba.tables.view.SegmentsBdvView.showSource(SegmentsBdvView.java:367)
	at de.embl.cba.tables.view.SegmentsBdvView.showSourceSet(SegmentsBdvView.java:295)
	at de.embl.cba.tables.view.SegmentsBdvView.showInitialSources(SegmentsBdvView.java:182)
	at de.embl.cba.tables.view.SegmentsBdvView.<init>(SegmentsBdvView.java:125)
	at de.embl.cba.tables.view.combined.SegmentsTableBdvAnd3dViews.bdvView(SegmentsTableBdvAnd3dViews.java:118)
	at de.embl.cba.tables.view.combined.SegmentsTableBdvAnd3dViews.show(SegmentsTableBdvAnd3dViews.java:63)
	at de.embl.cba.tables.view.combined.SegmentsTableBdvAnd3dViews.<init>(SegmentsTableBdvAnd3dViews.java:49)
	at de.embl.cba.mobie.viewer.SourcesPanel.showAnnotatedLabelsSource(SourcesPanel.java:454)
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToViewer(SourcesPanel.java:354)
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:338)
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:295)
	at de.embl.cba.mobie.viewer.ActionPanel.lambda$null$8(ActionPanel.java:433)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by constantinpape** [comment]
I just checked with the latest version from the MoBIE update site and it works on Linux.
Indeed looks like an issue with loading the table.

**Comment by K-Meech** [comment]
Just tried this again with a fresh fiji / mobie download - and it works fine. There must have been something wrong with my local fiji installation...
