### ISSUE TITLE
cannot load mobie

### ISSUE THREAD

**Issue by HernandoMV** [mobie/platybrowser-datasets#73]
after updating, MoBie GUI does not open, though the EM data loads

Adding source: sbem-6dpf-1-whole-raw...
[ERROR] Module threw error
java.lang.NoSuchMethodError: de.embl.cba.bdv.utils.BdvUtils.getShortCutString(Ljava/lang/String;)Ljava/lang/String;
	at de.embl.cba.mobie.ui.viewer.ActionPanel.installBdvBehavioursAndPopupMenu(ActionPanel.java:105)
	at de.embl.cba.mobie.ui.viewer.ActionPanel.setBdvAndInstallBehavioursAndPopupMenu(ActionPanel.java:79)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:100)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:50)
	at de.embl.cba.mobie.ui.command.OpenPlatyBrowserCommand.run(OpenPlatyBrowserCommand.java:16)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by K-Meech** [comment]
This works for me on the latest MoBIE - how are you opening MoBIE? Are you using 'Open MoBIE Project...' and https://github.com/mobie/platybrowser-datasets as the location?

**Comment by K-Meech** [comment]
Also, you're using the MoBIE update site and have the old 'EMBL-CBA' disabled?

**Comment by HernandoMV** [comment]
I was doing Open Platybrowser.
I am doing what you suggested and I get the same problem. I had a different location though

**Comment by HernandoMV** [comment]
whops, I broke Fiji when I disabled EMBL-CBA... :( 
will reinstall Thanks!

**Comment by HernandoMV** [comment]
No problem now :)
