### ISSUE TITLE
Platybrowser doesn't load

### ISSUE THREAD

**Issue by vzinche** [mobie/platybrowser-datasets#74]
When I start the default platybrowser I get these errors. Does anyone else also have it, or is it just me? It is for the mobie-beta update site, and I have all the recent image-j updates 

Console:
[ERROR] Module threw exception
java.lang.NullPointerException
	at de.embl.cba.mobie.n5.N5ImageLoader.createSetupImgLoader(N5ImageLoader.java:164)
	at de.embl.cba.mobie.n5.N5ImageLoader.open(N5ImageLoader.java:112)
	at de.embl.cba.mobie.n5.N5ImageLoader.getSetupImgLoader(N5ImageLoader.java:156)
	at de.embl.cba.mobie.n5.N5ImageLoader.getSetupImgLoader(N5ImageLoader.java:73)
	at bdv.BigDataViewer.initSetupNumericType(BigDataViewer.java:261)
	at bdv.BigDataViewer.initSetups(BigDataViewer.java:293)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.initSpimData(LazySpimSource.java:92)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.wrappedVolatileSource(LazySpimSource.java:66)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:137)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:48)
	at bdv.util.BdvFunctions.addSource(BdvFunctions.java:581)
	at bdv.util.BdvFunctions.show(BdvFunctions.java:196)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.showIntensitySource(SourcesPanel.java:387)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToViewer(SourcesPanel.java:364)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:339)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:296)
	at de.embl.cba.mobie.bookmark.BookmarksManager.addSourcesToPanelAndViewer(BookmarksManager.java:53)
	at de.embl.cba.mobie.bookmark.BookmarksManager.setView(BookmarksManager.java:35)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:87)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:52)
	at de.embl.cba.mobie.ui.command.OpenPlatyBrowserCommand.run(OpenPlatyBrowserCommand.java:16)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Exception:
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.NullPointerException
	at de.embl.cba.mobie.n5.N5ImageLoader.createSetupImgLoader(N5ImageLoader.java:164)
	at de.embl.cba.mobie.n5.N5ImageLoader.open(N5ImageLoader.java:112)
	at de.embl.cba.mobie.n5.N5ImageLoader.getSetupImgLoader(N5ImageLoader.java:156)
	at de.embl.cba.mobie.n5.N5ImageLoader.getSetupImgLoader(N5ImageLoader.java:73)
	at bdv.BigDataViewer.initSetupNumericType(BigDataViewer.java:261)
	at bdv.BigDataViewer.initSetups(BigDataViewer.java:293)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.initSpimData(LazySpimSource.java:92)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.wrappedVolatileSource(LazySpimSource.java:66)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:137)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:48)
	at bdv.util.BdvFunctions.addSource(BdvFunctions.java:581)
	at bdv.util.BdvFunctions.show(BdvFunctions.java:196)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.showIntensitySource(SourcesPanel.java:387)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToViewer(SourcesPanel.java:364)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:339)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:296)
	at de.embl.cba.mobie.bookmark.BookmarksManager.addSourcesToPanelAndViewer(BookmarksManager.java:53)
	at de.embl.cba.mobie.bookmark.BookmarksManager.setView(BookmarksManager.java:35)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:87)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:52)
	at de.embl.cba.mobie.ui.command.OpenPlatyBrowserCommand.run(OpenPlatyBrowserCommand.java:16)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more

cc @tischi @constantinpape @K-Meech

**Comment by constantinpape** [comment]
Yes, this is an issue with the EMBL s3, Josep is trying to fix it.
See https://github.com/mobie/mobie/issues/18.

**Comment by vzinche** [comment]
Sorry, I've missed this one
