### ISSUE TITLE
Browsing with table very slow

### ISSUE THREAD

**Issue by HernandoMV** [mobie/platybrowser-datasets#78]
Issue happening when loading cell segmentation and appending own column. Everything becomes extremely slow, and this error shows up constantly:

java.util.concurrent.ExecutionException: java.io.IOException: Gzip-compressed data is corrupt
	at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:112)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.get(LoaderCacheKeyAdapter.java:20)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:43)
	at net.imglib2.cache.ref.WeakRefVolatileCache.getBlocking(WeakRefVolatileCache.java:451)
	at net.imglib2.cache.ref.WeakRefVolatileCache.access$000(WeakRefVolatileCache.java:20)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:498)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:475)
	at net.imglib2.cache.queue.FetcherThreads$Fetcher.run(FetcherThreads.java:177)
Caused by: java.io.IOException: Gzip-compressed data is corrupt
	at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.read(GzipCompressorInputStream.java:316)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at org.janelia.saalfeldlab.n5.DefaultBlockReader.read(DefaultBlockReader.java:51)
	at org.janelia.saalfeldlab.n5.DefaultBlockReader.readBlock(DefaultBlockReader.java:91)
	at org.janelia.saalfeldlab.n5.s3.N5AmazonS3Reader.readBlock(N5AmazonS3Reader.java:252)
	at de.embl.cba.mobie.n5.N5ImageLoader$N5CacheArrayLoader.loadArray(N5ImageLoader.java:321)
	at bdv.img.cache.VolatileGlobalCellCache.lambda$createImg$1(VolatileGlobalCellCache.java:246)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.lambda$get$0(LoaderCacheKeyAdapter.java:22)
	at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:102)
	... 7 more

**Comment by constantinpape** [comment]
Oh, I had hoped that these issues don't occur for the platybrowser...
I am re-uploading the segmentation, that should fix it.
I will let you know when you can test again.

**Comment by constantinpape** [comment]
@HernandoMV the upload is done, I hope this fixes the problem.
Let me know once you had time to test it again.

**Comment by constantinpape** [comment]
This was connected to broken data and the problem is fixed.
