### ISSUE TITLE
Platy browser doesn't work - Amazon S3 exception

### ISSUE THREAD

**Issue by vzinche** [mobie/platybrowser-datasets#79]
@constantinpape @tischi do you guys have the same? Any idea whether its a problem of ours or an issue from Amazon's side? 

Exception in thread "PainterThread" java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.amazonaws.services.s3.model.AmazonS3Exception: Service Unavailable (Service: Amazon S3; Status Code: 503; Error Code: 503 Service Unavailable; Request ID: 1657ED583DA52515; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:45)
	at bdv.AbstractSpimSource.getSource(AbstractSpimSource.java:230)
	at bdv.AbstractSpimSource.getSource(AbstractSpimSource.java:222)
	at bdv.tools.transformation.TransformedSource.getSource(TransformedSource.java:218)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getSource(LazySpimSource.java:119)
	at bdv.tools.transformation.TransformedSource.getSource(TransformedSource.java:218)
	at bdv.viewer.render.MultiResolutionRenderer.prefetch(MultiResolutionRenderer.java:813)
	at bdv.viewer.render.MultiResolutionRenderer.createSingleSourceVolatileProjector(MultiResolutionRenderer.java:764)
	at bdv.viewer.render.MultiResolutionRenderer.createSingleSourceProjector(MultiResolutionRenderer.java:724)
	at bdv.viewer.render.MultiResolutionRenderer.createProjector(MultiResolutionRenderer.java:651)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:510)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:482)
	at net.imglib2.ui.PainterThread.run(PainterThread.java:86)
Caused by: java.util.concurrent.ExecutionException: com.amazonaws.services.s3.model.AmazonS3Exception: Service Unavailable (Service: Amazon S3; Status Code: 503; Error Code: 503 Service Unavailable; Request ID: 1657ED583DA52515; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
	at net.imglib2.cache.ref.WeakRefLoaderCache.get(WeakRefLoaderCache.java:112)
	at net.imglib2.cache.ref.BoundedSoftRefLoaderCache.get(BoundedSoftRefLoaderCache.java:54)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:43)
	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:41)

**Comment by constantinpape** [comment]
Yes, I can't access the dataset on s3 either / or it takes very long.
It's probably an issue on the embl s3. I will open an issue about it.

**Comment by constantinpape** [comment]
Works again.
